In [29]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [2]:
(train_x,train_y),(test_x,test_y) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [3]:
print("train shape :",train_x.shape)
print("Test shape :",test_x.shape)
print("Actual Train Output",train_y.shape)
print("Actual Test Output",test_y.shape)

train shape : (404, 13)
Test shape : (102, 13)
Actual Train Output (404,)
Actual Test Output (102,)


In [4]:
train_x

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [5]:
train_y

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [6]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [7]:
test_x[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [8]:
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
def HousePricePredictionModel():
  model=Sequential()
  model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
  model.add(Dense(64,activation='relu'))
  model.add(Dense(32,activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model


In [15]:
import numpy as np
k=4
num_val_samples= len(train_x)
num_epochs = 100
all_scores = []

In [16]:
model = HousePricePredictionModel()
history=model.fit(x=train_x,y=train_y,epochs= num_epochs,batch_size=1,verbose=1,validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 2s 3ms/step - loss: 144.8453 - mae: 8.5656 - val_loss: 77.4355 - val_mae: 6.2103
Epoch 2/100
404/404 [==============================] - 1s 4ms/step - loss: 67.5806 - mae: 5.8281 - val_loss: 71.2374 - val_mae: 5.9722
Epoch 3/100
404/404 [==============================] - 1s 4ms/step - loss: 64.1747 - mae: 5.5599 - val_loss: 58.1343 - val_mae: 5.5499
Epoch 4/100
404/404 [==============================] - 1s 2ms/step - loss: 59.8573 - mae: 5.4277 - val_loss: 75.4755 - val_mae: 6.1232
Epoch 5/100
404/404 [==============================] - 1s 2ms/step - loss: 58.8780 - mae: 5.2110 - val_loss: 62.0705 - val_mae: 5.5735
Epoch 6/100
404/404 [==============================] - 1s 2ms/step - loss: 56.9864 - mae: 5.2444 - val_loss: 60.1770 - val_mae: 5.4770
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 57.1133 - mae: 5.0859 - val_loss: 51.2449 - val_mae: 5.3288
Epoch 8/100
404/404 [==============================] -

In [17]:
test_x[0]

array([0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
       0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
       0.02988655, 0.04031725, 0.04298041])

In [28]:
test = [test_x[0].tolist()];
print("Actual Output: ", test_y[0])
print("Predicted Output: ", model.predict(test))

test = [test_x[1].tolist()];
print("Actual Output: ", test_y[1])
print("Predicted Output: ", model.predict(test))

test = [test_x[2].tolist()];
print("Actual Output: ", test_y[2])
print("Predicted Output: ", model.predict(test))

Actual Output:  7.2
1/1 [==============================] - 0s 38ms/step
Predicted Output:  [[10.166481]]
Actual Output:  18.8
1/1 [==============================] - 0s 36ms/step
Predicted Output:  [[18.866968]]
Actual Output:  19.0
1/1 [==============================] - 0s 35ms/step
Predicted Output:  [[23.140656]]
